[profile.default]
src = "contracts"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
via_ir = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
]

[rpc_endpoints]
lisk_sepolia = "${RPC_URL}"
